### PR TITLE
Rewrite of authCheck

### PR DESCRIPTION
**Pull request by atwardowski**
I was having issues with authCheck randomly removing roles from our users, and when I went to debug it I ended up just rewriting most of the class, and here are the results.  Some of the logic in the original file seemed bizzare to me, but maybe it was there for some features that I didn't know about.  This should definitely go through some more testing if you decide to merge it, but it seems to be working on our bot.

### CODE REVIEW

**Comment by shibdib** [comment]
1. I like the formatting, as someone self taught in php learning as I go this is something I can base future refactors off of.

2. I don't see any checks for if ESI is up (Which probably got added after you did this). Which is what was the actual cause of most of the role removals. Is it in there and I just missed it?

**Comment by atwardowski** [comment]
The idea is that getCharacterDetails() and getCorpDetails() will throw an exception if there is an error with a lookup, and that exception will get caught in the checkPermissions() loop and generate a log message.  I just pushed another commit too to catch an exception I missed that just showed up in my log and end the loop if TQ is unavailable.

**Comment by shibdib** [comment]
I think the issue is those catches have been in the functions for awhile, they just don't actually catch the errors because the page returns fine just without the info. 

Outside of a well organized refactor I don't see how this fixed the issue of roles being removed when esi is down.

**Comment by atwardowski** [comment]
I think you are taking about the code in eveApi.php.  I'm talking about the new functions in authCheck.php.  If the API returns null or has an error key set they will throw an exception.

https://github.com/atwardowski/Dramiel/blob/874ce37f31d9c2610a363ff76e0a276918662db1/src/plugins/onTick/authCheck.php#L175

And

https://github.com/atwardowski/Dramiel/blob/874ce37f31d9c2610a363ff76e0a276918662db1/src/plugins/onTick/authCheck.php#L196

And get caught here

https://github.com/atwardowski/Dramiel/blob/874ce37f31d9c2610a363ff76e0a276918662db1/src/plugins/onTick/authCheck.php#L317

It's possible there's some situation where the API call doesn't report an error and also doesn't contain the necessary data, but I haven't seen that.  It would be trivial to update those functions to check for every key in the API result before deciding to throw or return.

**Pull request merged**
